package com.liferay.blade.cli.custom;
import com.liferay.blade.cli.BaseCommand;
import com.liferay.blade.cli.BladeCLI;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class CustomCommand extends BaseCommand<CustomArgs>{
    public CustomCommand(BladeCLI blade, CustomArgs args) {
		super(blade, args);
	}

	public boolean someLibraryMethod() {
    	
        return true;
    }

	@Override
	public void execute() throws Exception {
		System.out.println("Hello from CustomCommand!");
	}
}
